version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: 3xui_bot_db
    environment:
      POSTGRES_USER: bot_user
      POSTGRES_PASSWORD: bot_password_2024
      POSTGRES_DB: 3xui_bot
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  postgres_data:
